<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<UseWPF>true</UseWPF>
		<Copyright>Copyright © DRONA 2021</Copyright>
		<TargetFramework>net5.0-windows</TargetFramework>
		<LangVersion>latest</LangVersion>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<Nullable>enable</Nullable>
		<UserSecretsId>15fae26a-b280-410f-a3a2-ccf9337fb385</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="EasyInsur.db" />
		<None Remove="images\no_image.jpg" />
		<None Remove="Resources\address.png" />
		<None Remove="Resources\add_people.png" />
		<None Remove="Resources\agent.png" />
		<None Remove="Resources\broker.ico" />
		<None Remove="Resources\broker_16.png" />
		<None Remove="Resources\broker_32.png" />
		<None Remove="Resources\clear.png" />
		<None Remove="Resources\customer.png" />
		<None Remove="Resources\dashboard.png" />
		<None Remove="Resources\email.png" />
		<None Remove="Resources\isd_country_code.json" />
		<None Remove="Resources\link.png" />
		<None Remove="Resources\man.png" />
		<None Remove="Resources\money.png" />
		<None Remove="Resources\noProfile.png" />
		<None Remove="Resources\no_image.jpg" />
		<None Remove="Resources\payment_history.png" />
		<None Remove="Resources\people.png" />
		<None Remove="Resources\phone.png" />
		<None Remove="Resources\rtolist.pdf" />
		<None Remove="Resources\rupee.png" />
		<None Remove="Resources\save.png" />
		<None Remove="Resources\telegram.png" />
		<None Remove="Resources\view_people.png" />
		<None Remove="Resources\wall.jpg" />
		<None Remove="Resources\website.png" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="EasyInsur.db">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="Resources\isd_country_code.json" />
	</ItemGroup>
	<ItemGroup>
	  <None Include="..\.editorconfig" Link=".editorconfig" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="HandyControls" Version="3.3.7" />
		<PackageReference Include="libphonenumber-csharp" Version="8.12.32" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
		<PackageReference Include="Prism.DryIoc" Version="8.1.97" />
		<PackageReference Include="Prism.Wpf" Version="8.1.97" />
		<PackageReference Include="RepoDb.SqLite" Version="1.1.3" />
		<PackageReference Include="Syncfusion.DataGridExcelExport.Wpf" Version="19.2.0.62" />
		<PackageReference Include="Syncfusion.Themes.FluentLight.WPF" Version="19.2.0.62" />
		<PackageReference Include="System.Data.SQLite.Core" Version="1.0.115" />
		<PackageReference Include="Syncfusion.Shared.WPF" Version="19.2.0.62" />
		<PackageReference Include="Syncfusion.SfImageEditor.WPF" Version="19.2.0.62" />
		<PackageReference Include="Syncfusion.SfGrid.WPF" Version="19.2.0.62" />
		<PackageReference Include="Syncfusion.Themes.Metro.Wpf" Version="19.2.0.62" />
		<PackageReference Include="Syncfusion.SfSkinManager.Wpf" Version="19.2.0.62" />
    <PackageReference Include="Syncfusion.SfInput.WPF" Version="19.2.0.62" />
    <PackageReference Include="Syncfusion.SfBarcode.WPF" Version="19.2.0.62" />
</ItemGroup>
	<ItemGroup>
		<Content Include="images\no_image.jpg">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Resource Include="Resources\address.png" />
		<Resource Include="Resources\add_people.png" />
		<Resource Include="Resources\agent.png" />
		<Resource Include="Resources\broker.ico" />
		<Resource Include="Resources\broker_16.png" />
		<Resource Include="Resources\broker_32.png" />
		<Content Include="Resources\rtolist.pdf">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Resource Include="Resources\clear.png" />
		<Resource Include="Resources\customer.png" />
		<Resource Include="Resources\dashboard.png" />
		<Resource Include="Resources\email.png" />
		<Resource Include="Resources\link.png" />
		<Resource Include="Resources\man.png" />
		<Resource Include="Resources\money.png" />
		<Resource Include="Resources\noProfile.png" />
		<Resource Include="Resources\no_image.jpg" />
		<Resource Include="Resources\payment_history.png" />
		<Resource Include="Resources\people.png" />
		<Resource Include="Resources\phone.png" />
		<Resource Include="Resources\rupee.png" />
		<Resource Include="Resources\save.png" />
		<Resource Include="Resources\telegram.png" />
		<Resource Include="Resources\view_people.png" />
		<Resource Include="Resources\wall.jpg" />
		<Resource Include="Resources\website.png" />
	</ItemGroup>

</Project>
